/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServersServerIdRouteImport } from './routes/servers/$serverId'
import { ServerRoute as ApiWebhooksMittwaldServerRouteImport } from './routes/api/webhooks.mittwald'

const rootServerRouteImport = createServerRootRoute()

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersServerIdRoute = ServersServerIdRouteImport.update({
  id: '/$serverId',
  path: '/$serverId',
  getParentRoute: () => ServersRoute,
} as any)
const ApiWebhooksMittwaldServerRoute =
  ApiWebhooksMittwaldServerRouteImport.update({
    id: '/api/webhooks/mittwald',
    path: '/api/webhooks/mittwald',
    getParentRoute: () => rootServerRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/servers': typeof ServersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/servers/$serverId': typeof ServersServerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/servers': typeof ServersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/servers/$serverId': typeof ServersServerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/servers': typeof ServersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/servers/$serverId': typeof ServersServerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/servers' | '/settings' | '/servers/$serverId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/servers' | '/settings' | '/servers/$serverId'
  id: '__root__' | '/' | '/servers' | '/settings' | '/servers/$serverId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServersRoute: typeof ServersRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}
export interface FileServerRoutesByFullPath {
  '/api/webhooks/mittwald': typeof ApiWebhooksMittwaldServerRoute
}
export interface FileServerRoutesByTo {
  '/api/webhooks/mittwald': typeof ApiWebhooksMittwaldServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/webhooks/mittwald': typeof ApiWebhooksMittwaldServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/webhooks/mittwald'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/webhooks/mittwald'
  id: '__root__' | '/api/webhooks/mittwald'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiWebhooksMittwaldServerRoute: typeof ApiWebhooksMittwaldServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$serverId': {
      id: '/servers/$serverId'
      path: '/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ServersServerIdRouteImport
      parentRoute: typeof ServersRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/webhooks/mittwald': {
      id: '/api/webhooks/mittwald'
      path: '/api/webhooks/mittwald'
      fullPath: '/api/webhooks/mittwald'
      preLoaderRoute: typeof ApiWebhooksMittwaldServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface ServersRouteChildren {
  ServersServerIdRoute: typeof ServersServerIdRoute
}

const ServersRouteChildren: ServersRouteChildren = {
  ServersServerIdRoute: ServersServerIdRoute,
}

const ServersRouteWithChildren =
  ServersRoute._addFileChildren(ServersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServersRoute: ServersRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiWebhooksMittwaldServerRoute: ApiWebhooksMittwaldServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
